# Generated by Django 4.2.6 on 2023-10-12 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='mapp',
            new_name='map',
        ),
    ]
