# Generated by Django 4.2.6 on 2023-10-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_rename_mapp_country_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('imdbID', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('poster', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'movies',
                'ordering': ['title'],
            },
        ),
    ]
